// Scrollbar stylesheet for the emitted Starlight site: one thin, token-driven bar on every scroller
// (page, sidebar, table of contents, tables, code blocks, search dialog, mobile menu).
//
// The thumb is Starlight's `--sl-color-white` (near-white in dark, near-black in light) at 50%, 70%
// on hover. Over the page, sidebar and nav surfaces of both themes that stays above 3:1 (WCAG
// 1.4.11). The three `--scrollbar-*` tokens are the override point: a later customCss file or the
// site owner's own sheet can redefine them. Browsers without `scrollbar-color` get a 12px webkit
// bar with the thumb drawn 3px inside it; forced colors and `prefers-contrast: more` hand the bar
// back to the system. Nothing here hides a scrollbar.
//
// customCss is unlayered, so these rules beat Starlight's layered component CSS, including the
// table of contents' `scrollbar-width: none`.

/** Path of the emitted stylesheet, relative to the site root. */
export const SCROLLBARS_CSS_PATH = "src/styles/scrollbars.css";

/** Thumb opacity over `--sl-color-white`, idle and hovered. */
export const SCROLLBAR_THUMB_ALPHA = 0.5;
export const SCROLLBAR_THUMB_HOVER_ALPHA = 0.7;

const pct = (alpha: number): number => Math.round(alpha * 100);

export const SCROLLBARS_CSS = `/* Generated by docsxai — thin scrollbars on every scroller. No remote imports. */
:root {
  --scrollbar-track: transparent;
  --scrollbar-thumb: color-mix(in srgb, var(--sl-color-white) ${pct(SCROLLBAR_THUMB_ALPHA)}%, transparent);
  --scrollbar-thumb-hover: color-mix(in srgb, var(--sl-color-white) ${pct(SCROLLBAR_THUMB_HOVER_ALPHA)}%, transparent);
}

:root,
* {
  scrollbar-width: thin;
  scrollbar-color: var(--scrollbar-thumb) var(--scrollbar-track);
}

/* Browsers without scrollbar-color: a 12px hit area with a thumb drawn 3px inside it. */
@supports not (scrollbar-color: auto) {
  * {
    scrollbar-width: auto;
  }
  ::-webkit-scrollbar {
    width: 12px;
    height: 12px;
  }
  ::-webkit-scrollbar-track {
    background: var(--scrollbar-track);
  }
  ::-webkit-scrollbar-thumb {
    background: var(--scrollbar-thumb);
    border: 3px solid transparent;
    background-clip: content-box;
    border-radius: 6px;
  }
  ::-webkit-scrollbar-thumb:hover {
    background: var(--scrollbar-thumb-hover);
    background-clip: content-box;
  }
}

/* High-contrast users keep their system scrollbar. */
@media (forced-colors: active), (prefers-contrast: more) {
  :root,
  * {
    scrollbar-width: auto;
    scrollbar-color: auto;
  }
}
`;
