#!/usr/bin/env bash
# Block git commits that contain AI attribution trailers or credit lines.

set -euo pipefail

payload="$(cat)"
command="$(
  printf '%s' "$payload" \
    | jq -r '.tool_input.command // .command // empty' 2>/dev/null \
    || true
)"

if [[ -z "$command" || ! "$command" =~ git[[:space:]]+commit ]]; then
  exit 0
fi

if printf '%s' "$command" | grep -qiE '(co-authored-by:[[:space:]].*(claude|anthropic|openai|codex|gpt|copilot|ai)|generated[[:space:]]+(with|by)[[:space:]].*(claude|anthropic|openai|codex|gpt|copilot|ai)|noreply@anthropic\.com|openai.*codex)'; then
  jq -n '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: "BLOCKED: Commit messages must not include AI attribution. Remove Co-Authored-By, Generated by/with, and AI credit lines."
    }
  }'
fi
